#!/usr/bin/env python3
"""
claude-review.py — Analyze a GitHub PR diff and emit a structured Markdown
review comment (summary, risks, suggestions, confidence score).

Works as a CLI:
    python3 claude-review.py --pr https://github.com/owner/repo/pull/123
    python3 claude-review.py --pr 123 --repo owner/repo --format json

Requires: GITHUB_TOKEN in environment for private repos or rate-limited
public access. Uses only the GitHub REST API (no extra deps beyond stdlib).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from urllib.request import Request, urlopen
from urllib.error import HTTPError

API = "https://api.github.com"


def _gh(method: str, url: str, token: str | None, data=None) -> dict:
    headers = {"Accept": "application/vnd.github+json", "User-Agent": "claude-review"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    body = json.dumps(data).encode() if data is not None else None
    req = Request(url, data=body, headers=headers, method=method)
    try:
        with urlopen(req, timeout=30) as r:
            return json.loads(r.read().decode())
    except HTTPError as e:
        raise SystemExit(f"GitHub API error {e.code}: {e.read().decode()[:300]}")


def parse_pr_url(url: str) -> tuple[str, int]:
    m = re.search(r"github\.com/([^/]+/[^/]+)/pull/(\d+)", url)
    if not m:
        raise SystemExit("Could not parse PR URL. Use https://github.com/owner/repo/pull/123")
    return m.group(1), int(m.group(2))


def risk_keywords(diff: str) -> list[str]:
    risks = []
    if re.search(r"^\+\s*(DELETE|DROP|TRUNCATE|rm\s)", diff, re.M): risks.append("Destructive data operation (DELETE/DROP/TRUNCATE/rm) added")
    if "password" in diff.lower() or "secret" in diff.lower() or "api_key" in diff.lower(): risks.append("Possible secret/key hardcoded")
    if re.search(r"^\+\s*subprocess\.", diff, re.M): risks.append("Subprocess invocation added — injection surface")
    if re.search(r"eval\(|exec\(", diff): risks.append("eval()/exec() usage — code-injection risk")
    if re.search(r"https?://", diff) and "verify=" in diff: risks.append("TLS verification possibly disabled")
    if diff.count("+") - diff.count("-") > 200: risks.append("Very large change (>200 added lines) — review carefully")
    return risks


def suggest(diff: str) -> list[str]:
    sug = []
    if re.search(r"^\+\s*(print|console\.log|debugger)", diff, re.M): sug.append("Remove debug print/log statements before merge")
    if "TODO" in diff or "FIXME" in diff: sug.append("Resolve or ticket the TODO/FIXME left in code")
    if re.search(r"^\+\s*function\s|^\+\s*def\s", diff, re.M) and "test" not in diff.lower(): sug.append("Add tests for the new functions")
    if re.search(r"^\+\s*(import|require)\s", diff, re.M) and "lock" not in diff: sug.append("Ensure new dependencies are pinned in lockfile")
    return sug


def confidence(score_inputs: dict) -> str:
    added_tests = score_inputs["added_tests"]
    size = score_inputs["size"]
    if added_tests and size < 100: return "High"
    if size < 250: return "Medium"
    return "Low"


def review(pr_url: str, token: str | None, fmt: str = "markdown") -> str:
    repo, num = parse_pr_url(pr_url)
    pr = _gh("GET", f"{API}/repos/{repo}/pulls/{num}", token)
    files = _gh("GET", f"{API}/repos/{repo}/pulls/{num}/files?per_page=100", token)
    diff_parts = [f["patch"] or "" for f in files if f.get("patch")]
    full_diff = "\n".join(diff_parts)
    changed = [f["filename"] for f in files]

    risks = risk_keywords(full_diff)
    sugg = suggest(full_diff)
    conf = confidence({"added_tests": "test" in full_diff.lower(), "size": full_diff.count("\n")})

    if fmt == "json":
        return json.dumps({
            "pr": pr_url, "title": pr.get("title"), "changed_files": changed,
            "risks": risks, "suggestions": sugg, "confidence": conf,
        }, indent=2)

    lines = [
        f"## 🤖 Automated PR Review — #{num}",
        "",
        f"**Title:** {pr.get('title')}",
        f"**Changed files ({len(changed)}):** " + ", ".join(changed[:15]) + (" …" if len(changed) > 15 else ""),
        "",
        "### Summary",
        f"- State: {pr.get('state')} · Mergable: {pr.get('mergeable')}",
        f"- Additions: {pr.get('additions')} · Deletions: {pr.get('deletions')}",
        "",
        "### Identified Risks",
    ]
    lines += [f"- ⚠️ {r}" for r in risks] or ["- None detected by static heuristics."]
    lines += ["", "### Improvement Suggestions"]
    lines += [f"- 💡 {s}" for s in sugg] or ["- None."]
    lines += ["", f"### Confidence: **{conf}**", "",
              "_Generated by claude-review.py — heuristic static analysis, not a substitute for human review._"]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pr", required=True, help="PR URL or number (use --repo with number)")
    ap.add_argument("--repo", default=None, help="owner/repo (when --pr is just a number)")
    ap.add_argument("--format", choices=["markdown", "json"], default="markdown")
    args = ap.parse_args()
    token = os.environ.get("GITHUB_TOKEN")
    url = args.pr
    if args.repo and args.pr.isdigit():
        url = f"https://github.com/{args.repo}/pull/{args.pr}"
    print(review(url, token, args.format))


if __name__ == "__main__":
    main()
